//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::D4, // Ignition 1 (StockCoil)
	Gpio::G3, // Ignition 1 (Aux)
	Gpio::G4, // Ignition 2 (Aux)
	Gpio::G5, // Ignition 3 (Aux)
	Gpio::G6, // Ignition 4 (Aux)
	Gpio::G7, // Ignition 5 (Aux)
	Gpio::G8, // Ignition 6 (Aux)
	Gpio::G12, // Injector 1 (Stock)
	Gpio::G13, // Injector 2 (Stock)
	Gpio::G11, // Injector 3 (Stock)
	Gpio::E1, // Injector 4 (Stock)
	Gpio::E2, // Injector 5 (Stock)
	Gpio::G14, // Injector 6 (Stock)
	Gpio::G9, // Injector 1 (Aux)
	Gpio::G10, // Injector 2 (Aux)
	Gpio::D3, // Injector 3 (Aux)
	Gpio::D7, // Injector 4 (Aux)
	Gpio::A8, // Injector 5 (Aux)
	Gpio::A9, // Injector 6 (Aux)
	Gpio::E0, // Fuel Pump
	Gpio::E5, // NOS (PE5)
	Gpio::B8, // Tach (PB8)
	Gpio::B9, // Boost (PB9)
	Gpio::D11, // ETB_DIS/StepDir
	Gpio::D10, // ETB_DIR/StepStep
	Gpio::C5, // PPS2 (PC5)
	Gpio::D12, // ETB PWM
	Gpio::D15, // Fan1
	Gpio::D14, // Fan2
	Gpio::A6, // xxxx
	Gpio::E14, // Extra I/O PE14
	Gpio::E15, // Idle (PE15)
// "Ignition 1 (StockCoil)",
// "Ignition 1 (Aux)",
// "Ignition 2 (Aux)",
// "Ignition 3 (Aux)",
// "Ignition 4 (Aux)",
// "Ignition 5 (Aux)",
// "Ignition 6 (Aux)",
// "Injector 1 (Stock)",
// "Injector 2 (Stock)",
// "Injector 3 (Stock)",
// "Injector 4 (Stock)",
// "Injector 5 (Stock)",
// "Injector 6 (Stock)",
// "Injector 1 (Aux)",
// "Injector 2 (Aux)",
// "Injector 3 (Aux)",
// "Injector 4 (Aux)",
// "Injector 5 (Aux)",
// "Injector 6 (Aux)",
// "Fuel Pump",
// "NOS (PE5)",
// "Tach (PB8)",
// "Boost (PB9)",
// "ETB_DIS/StepDir",
// "ETB_DIR/StepStep",
// "PPS2 (PC5)",
// "ETB PWM",
// "Fan1",
// "Fan2",
// "xxxx",
// "Extra I/O PE14",
// "Idle (PE15)",
}
